export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as CreatePost } from "./CreatePost/CreatePost";
export { default as Posts } from "./Posts/Posts";
export { default as Article } from "./Article/Article";
export { default as Home } from "./Home/Home";
export { default as GanttChart } from "./GanttChart/GanttChart";
export { default as Edit } from "./Edit/Edit";
export { default as Discussion } from "./Discussion/Discussion";
